### ISSUE TITLE
MUTANT QC metrics

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/vogue#238] opened 2021-04-13 11:26 UTC
1. Path for QC files here `/home/proj/production/mutant/cases/*/*.json`: `/home/proj/production/mutant/cases/*/results/ticketid_20210412.json`
2. Add these either as new dict similar to MicroSalt or make one of its own
3. No MultiQC for now

**Comment by hassanfa** [comment] 2021-04-13 12:57
related to https://github.com/Clinical-Genomics/cgp-sars-cov-2-sequencing/issues/27

I'll update this one and add more details later on.

**Comment by Mropat** [comment] 2022-02-25 19:47
duplicate of #273

**Closed by Mropat** 2022-02-25 19:47 UTC
